// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

package helpers

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Jamf-Concepts/jamfplatform-go-sdk/jamfplatform"
)

// cloudFrontPage is the body CloudFront served on the pro lane in run
// 34202213638, trimmed to the markup that decides the classification. Kept
// verbatim rather than reduced to "some HTML" because the whole question is
// whether the SDK separates this from Jamf Pro's own HTML error template, and a
// synthetic page proves nothing about a real one.
const cloudFrontPage = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>404 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
We can't connect to the server for this app or website at this time.
<PRE>
Generated by cloudfront (CloudFront) HTTP3 Server
Request ID: YUQftLkPfkIskyRXbupeY0_EQVmY6IDMo2vt6z6QJ5_B8U5HC3VzoQ&#x3D;&#x3D;
</PRE>
</BODY></HTML>`

// classicStatusPage is Jamf Pro's own 404 template, which every /proclassic
// path serves and which must keep reading as "gone".
const classicStatusPage = `<html><head><title>Status page</title></head>` +
	`<body><p>The server has not found anything matching the request URI</p></body></html>`

// errorFromGateway drives the real SDK against a stub serving one response, so
// the classification under test is the SDK's own and not a hand-built error
// this package happens to agree with. A stub is the only way to reach it: the
// marking lives in the SDK's unexported transport, so no exported constructor
// can produce a marked error and a fabricated one would pass whatever this
// package asserted.
func errorFromGateway(t *testing.T, status int, contentType, body string) error {
	t.Helper()

	mux := http.NewServeMux()
	mux.HandleFunc("/auth/token", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(map[string]any{
			"access_token": "tok", "token_type": "Bearer", "expires_in": 3600,
		}); err != nil {
			t.Errorf("writing token response: %v", err)
		}
	})
	mux.HandleFunc("/pro/v1/buildings/1", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", contentType)
		w.WriteHeader(status)
		if _, err := w.Write([]byte(body)); err != nil {
			t.Errorf("writing stub response: %v", err)
		}
	})

	srv := httptest.NewServer(mux)
	t.Cleanup(srv.Close)

	client := jamfplatform.NewClient(srv.URL, "cid", "secret",
		jamfplatform.WithMinRequestInterval(0),
		jamfplatform.WithTenantID("00000000-0000-0000-0000-000000000000"))

	var out map[string]any
	err := client.Transport().Do(context.Background(), http.MethodGet, "/pro/v1/buildings/1", nil, &out)
	if err == nil {
		t.Fatal("stub returned no error, so there is nothing to classify")
	}
	return err
}

// TestIsNotFoundError_EdgePageIsNotGone pins the reason IsEdgeBlocked exists: a
// 404 an edge served is not evidence the object is gone, and reading it as gone
// removes a live object from state on the next refresh. The classic template in
// the same table is what stops the fix from being a blunt "HTML 404 is never
// gone", which would break every /proclassic Read.
func TestIsNotFoundError_EdgePageIsNotGone(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		status      int
		contentType string
		body        string
		edge        bool
		notFound    bool
	}{
		{
			name:        "cloudfront 404 page did not reach Jamf",
			status:      http.StatusNotFound,
			contentType: "text/html",
			body:        cloudFrontPage,
			edge:        true,
			notFound:    false,
		},
		{
			name:        "classic status page is Jamf reporting a real not-found",
			status:      http.StatusNotFound,
			contentType: "text/html",
			body:        classicStatusPage,
			edge:        false,
			notFound:    true,
		},
		{
			name:        "pro json 404 is Jamf reporting a real not-found",
			status:      http.StatusNotFound,
			contentType: "application/json",
			body:        `{"httpStatus":404,"errors":[{"code":"NOT_FOUND","description":"no such building"}]}`,
			edge:        false,
			notFound:    true,
		},
		{
			name:        "gateway unrouted 404 is neither",
			status:      http.StatusNotFound,
			contentType: "text/plain; charset=utf-8",
			body:        "404 page not found\n",
			edge:        false,
			notFound:    false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			err := errorFromGateway(t, tc.status, tc.contentType, tc.body)

			if got := IsEdgeBlocked(err); got != tc.edge {
				t.Errorf("IsEdgeBlocked = %v, want %v", got, tc.edge)
			}
			if got := IsNotFoundError(err); got != tc.notFound {
				t.Errorf("IsNotFoundError = %v, want %v — reading an edge page as "+
					"\"gone\" deletes a live object from state, and refusing a real "+
					"Jamf 404 leaves a deleted object in it", got, tc.notFound)
			}
		})
	}
}

// nginxBlockPage is the other edge shape, and the one a WAF or IP allowlist
// serves: a 403 from nginx rather than a CloudFront failure page.
const nginxBlockPage = `<html>
<head><title>403 Forbidden</title></head>
<body><center><h1>403 Forbidden</h1></center><hr><center>nginx</center></body>
</html>`

// TestIsEdgeBlocked_KeepsTheAPIErrorReachable pins the property the fix rests
// on: the SDK wraps rather than replaces, so marking an error as an edge page
// must not cost the status, body or trace id the diagnostics read. If the SDK
// ever wraps without %w this fails here rather than as a nil dereference in one
// of the twenty-odd resource helpers that call AsAPIError.
//
// Driven with the 403 block page rather than a CloudFront 5xx deliberately. The
// assertion is about the wrapper and holds for any marked status, and a 5xx is
// one the SDK retries — which spent fifteen seconds of `make test` proving
// something this does not test.
func TestIsEdgeBlocked_KeepsTheAPIErrorReachable(t *testing.T) {
	t.Parallel()

	err := errorFromGateway(t, http.StatusForbidden, "text/html", nginxBlockPage)

	if !IsEdgeBlocked(err) {
		t.Fatalf("IsEdgeBlocked = false for an nginx 403 block page: %v", err)
	}

	apiErr := jamfplatform.AsAPIError(err)
	if apiErr == nil {
		t.Fatalf("AsAPIError = nil, so the *APIResponseError left the error chain: %v", err)
	}
	if apiErr.StatusCode != http.StatusForbidden {
		t.Errorf("StatusCode = %d, want %d", apiErr.StatusCode, http.StatusForbidden)
	}
	if IsNotFoundError(err) {
		t.Error("IsNotFoundError = true for a 403")
	}
}
