// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MPL-2.0

package computer_invitation

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// computerInvitationTimeoutAttributeTypes defines the timeout attribute types
// for the computer invitation resource operations.
var computerInvitationTimeoutAttributeTypes = map[string]attr.Type{
	"create": types.StringType,
	"read":   types.StringType,
	"update": types.StringType,
	"delete": types.StringType,
}

// validInvitationTypes is the set of user-creatable invitation_type values.
// DEP_CUSTOM_ENROLL is intentionally excluded — it is generated by the DEP /
// Automated Device Enrollment subsystem, not creatable through this API.
var validInvitationTypes = []string{
	"USER_INITIATED_URL",
	"USER_INITIATED_EMAIL",
}
